version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: bloomberg_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bloomberg_db
    ports:
      - "3306:3306"
